### ISSUE TITLE
Enhancement: Move critical CSS styles for above the fold into inline stylesheet

### ISSUE THREAD

**Issue by madcatsu** [nielsenramon/chalk#100]
Consider using tools like [Critical](https://github.com/addyosmani/critical) or [Grunt-critical](https://github.com/bezoerb/grunt-critical) to review and resolve PageSpeed Insights penalties for blocking CSS which defers rendering of important page elements until the page has completely sourced from the origin server.

**Comment by migueldemoura** [comment]
I'm a little torn on this one. Chalk's css size is negligible (3.812kB gzipped), and those optimizations are rather tricky. The proposed change would only reduce a couple kB of css to above the fold, and it would have to be made with extreme care, because UX is degraded when seeing moving/changing objects, being preferable to wait a few more ms. Plus, please take into account that PageSpeed recommendations are just that - recommendations -, [notoriously very general](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgsuite.google.com%2F) and not specific to each case.

**Comment by madcatsu** [comment]
@migueldemoura duly noted on the PageSpeed recommendations. I think one of the biggest killers to speed is loading webfonts and the ionicons font. I see #59 aims to address some of this :)

**Comment by nielsenramon** [comment]
@madcatsu I also don't want to over-engineer a simple theme for Jekyll. This is a theme for everyone and I would like to keep it open and accessible. I agree on the icon font tho. That needs to go :-) Closing this one. Thanks for the feedback!
