### ISSUE TITLE
Found error with npm run local

### ISSUE THREAD

**Issue by kjs1715** [nielsenramon/chalk#165]
![image](https://user-images.githubusercontent.com/39690946/42087476-e085cf82-7bc8-11e8-83b0-ed758b64c369.png)
I don t know how to deal with this...

**Comment by akashjobanputra** [comment]
Tried (chown)-ing the `.jukyll-cache` directory ?
```bash
sudo chown -R kim /Users/kim/Desktop/Git/kjs1715.github.io/.jekyll-cache
```

**Comment by kjs1715** [comment]
@akashjobanputra Ahh now I can run it but I can`t open my github.io...I already changed my repo name with myname.github.io, but it stil not working..

**Comment by akashjobanputra** [comment]
@kjs1715 Ok, for that you'll need to replace all the instances of word `gh-pages` to `master`, keep in mind that after doing that if you run `npm run publish` it will DELETE your master branch and will create it again to push the built blog on it.  
So before that, you can checkout your development code into a new branch (dev, or anything that suits you). And then do the above replacement in `bin/deploy` file.

That's because, personal or organization sites are built from master. gh-pages branch is used to build sites for projects.
