### ISSUE TITLE
Click the Page Title Only Show 3 Posts

### ISSUE THREAD

**Issue by 95uxin** [nielsenramon/chalk#67]
Anybody have this problem?

Click the title sometimes, but only show 3 posts. Can not see the footer.
Sometimes it works, sometimes it dose not.

**Comment by noahbishop** [comment]
That happened to me as well, I can't figure out how to replicate it though.

**Comment by nielsenramon** [comment]
@95uxin @noahbishop I think I found the issue, please see if it is fixed on latest master branch.

**Comment by 95uxin** [comment]
@nielsenramon 
I tried your newest master version.
**Better, but still have this problem!**
I sent you a video email.
QuickScrollDown may cause this issue.
QuickScrollDown uses Frequently to find the post you want.

**Comment by noahbishop** [comment]
I still have this issue. The remaining posts are there but their opacity is set to 0 which may confirm it is indeed a QuickScrollDown issue.

**Comment by noahbishop** [comment]
On further testing, I think this issue is not with Chalk. I have been able to reproduce the issue: It stems from me reusing the same page after restarting Jekyll.

I run `Jekyll serve`

Head over to `127.0.0.1:4000`

Interrupt the `Jekyll serve` command and run it again

Click on the title (on the page generated by the former command) and be met with 2 posts only.

So yeah, for me this was more of a usability issue on my end and not with Chalk per se.

**Comment by 95uxin** [comment]
@noahbishop 
I have  found a way to avoid this issue and uses on [my website](https://wuyu.xin).
Force Reload the page can help. (you can  click the **reload page button** on your browser, have a test)
The **link of the Page Title** I replaced from `/` to `http://mywebsite`.
But my website uses `https`. I redirect the http to https. This can cause a force reload.
